# Generated by Django 5.0.7 on 2024-07-23 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TUsers',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('users_id', models.BigAutoField(db_column='USERS_ID', editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=150, unique=True)),
                ('email', models.EmailField(db_column='EMAIL', max_length=254, unique=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('updated_by', models.CharField(blank=True, db_column='UPDATED_BY', max_length=150, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('deleted_by', models.CharField(blank=True, db_column='DELETED_BY', max_length=150, null=True)),
                ('x1', models.CharField(blank=True, db_column='X1', max_length=255, null=True)),
                ('x2', models.CharField(blank=True, db_column='X2', max_length=255, null=True)),
                ('x3', models.CharField(blank=True, db_column='X3', max_length=255, null=True)),
                ('x4', models.CharField(blank=True, db_column='X4', max_length=255, null=True)),
                ('x5', models.CharField(blank=True, db_column='X5', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'T_USERS',
                'managed': True,
            },
        ),
    ]
